apiVersion: v1
kind: ConfigMap
metadata:
  name: gestagro-config
  namespace: gestagro
data:
  DJANGO_SETTINGS_MODULE: "gestagro.settings.production"
  ALLOWED_HOSTS: "gestagro.com,api.gestagro.com"
  CORS_ALLOWED_ORIGINS: "https://gestagro.com,https://www.gestagro.com"
  MINIO_BUCKET_NAME: "gestagro-prod"
  ENVIRONMENT: "production"
