# Generated by Django 5.2.7 on 2025-10-26 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
        ("iam", "0002_alter_organization_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "variety",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="variety"
                    ),
                ),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("cereal", "Cereal"),
                            ("legume", "Legume"),
                            ("vegetable", "Vegetable"),
                            ("fruit", "Fruit"),
                            ("tuber", "Tuber"),
                            ("spice", "Spice"),
                            ("cash_crop", "Cash Crop"),
                        ],
                        max_length=20,
                        verbose_name="crop type",
                    ),
                ),
                ("planting_date", models.DateField(verbose_name="planting date")),
                (
                    "expected_harvest_date",
                    models.DateField(verbose_name="expected harvest date"),
                ),
                (
                    "actual_harvest_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="actual harvest date"
                    ),
                ),
                (
                    "planted_area_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="planted area (hectares)",
                    ),
                ),
                (
                    "expected_yield_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="expected yield (kg)",
                    ),
                ),
                (
                    "actual_yield_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="actual yield (kg)",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("dry", "Dry Season"),
                            ("rainy", "Rainy Season"),
                            ("all_year", "All Year"),
                        ],
                        max_length=20,
                        verbose_name="season",
                    ),
                ),
                (
                    "weather_conditions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="weather conditions"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planted", "Planted"),
                            ("growing", "Growing"),
                            ("flowering", "Flowering"),
                            ("fruiting", "Fruiting"),
                            ("harvested", "Harvested"),
                            ("failed", "Failed"),
                        ],
                        default="planted",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_crops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crops",
                        to="farmers.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop",
                "verbose_name_plural": "Crops",
                "db_table": "agronomy_crops",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "location",
                    models.JSONField(blank=True, default=dict, verbose_name="location"),
                ),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="area (hectares)"
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("clay", "Clay"),
                            ("sandy", "Sandy"),
                            ("loamy", "Loamy"),
                            ("silty", "Silty"),
                            ("peaty", "Peaty"),
                            ("chalky", "Chalky"),
                        ],
                        max_length=20,
                        verbose_name="soil type",
                    ),
                ),
                (
                    "ph_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="pH level",
                    ),
                ),
                (
                    "organic_matter_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="organic matter %",
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("manual", "Manual"),
                            ("drip", "Drip"),
                            ("sprinkler", "Sprinkler"),
                            ("flood", "Flood"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="irrigation type",
                    ),
                ),
                (
                    "water_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="water source"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "db_table": "agronomy_fields",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnostic_type",
                    models.CharField(
                        choices=[
                            ("soil_analysis", "Soil Analysis"),
                            ("pest_disease", "Pest/Disease Diagnosis"),
                            ("nutrient_deficiency", "Nutrient Deficiency"),
                            ("yield_analysis", "Yield Analysis"),
                            ("water_quality", "Water Quality"),
                            ("general_health", "General Health"),
                        ],
                        max_length=30,
                        verbose_name="diagnostic type",
                    ),
                ),
                ("diagnosis_date", models.DateTimeField(verbose_name="diagnosis date")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        verbose_name="severity",
                    ),
                ),
                ("findings", models.TextField(verbose_name="findings")),
                ("causes", models.TextField(blank=True, verbose_name="causes")),
                (
                    "impact_assessment",
                    models.TextField(blank=True, verbose_name="impact assessment"),
                ),
                (
                    "recommended_treatment",
                    models.TextField(blank=True, verbose_name="recommended treatment"),
                ),
                (
                    "treatment_cost_xaf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="treatment cost (XAF)",
                    ),
                ),
                (
                    "treatment_duration_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="treatment duration (days)"
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, verbose_name="follow up required"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="follow up date"
                    ),
                ),
                (
                    "photos",
                    models.JSONField(blank=True, default=list, verbose_name="photos"),
                ),
                (
                    "lab_results",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="lab results"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "agronomist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostics",
                        to="agronomy.crop",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostics",
                        to="agronomy.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnostic",
                "verbose_name_plural": "Diagnostics",
                "db_table": "agronomy_diagnostics",
                "ordering": ["-diagnosis_date"],
            },
        ),
        migrations.AddField(
            model_name="crop",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crops",
                to="agronomy.field",
            ),
        ),
        migrations.CreateModel(
            name="FieldVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Visit"),
                            ("inspection", "Inspection"),
                            ("consultation", "Consultation"),
                            ("emergency", "Emergency"),
                            ("harvest_preparation", "Harvest Preparation"),
                        ],
                        max_length=30,
                        verbose_name="visit type",
                    ),
                ),
                ("visit_date", models.DateTimeField(verbose_name="visit date")),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="duration (hours)",
                    ),
                ),
                (
                    "weather_conditions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="weather conditions"
                    ),
                ),
                (
                    "soil_conditions",
                    models.TextField(blank=True, verbose_name="soil conditions"),
                ),
                (
                    "crop_conditions",
                    models.TextField(blank=True, verbose_name="crop conditions"),
                ),
                (
                    "pest_disease_observations",
                    models.TextField(
                        blank=True, verbose_name="pest/disease observations"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="recommendations"),
                ),
                (
                    "next_visit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="next visit date"
                    ),
                ),
                (
                    "photos",
                    models.JSONField(blank=True, default=list, verbose_name="photos"),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="documents"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "agronomist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="agronomy.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Visit",
                "verbose_name_plural": "Field Visits",
                "db_table": "agronomy_field_visits",
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("fertilization", "Fertilization"),
                            ("irrigation", "Irrigation"),
                            ("pest_control", "Pest Control"),
                            ("disease_management", "Disease Management"),
                            ("harvest_timing", "Harvest Timing"),
                            ("crop_rotation", "Crop Rotation"),
                            ("soil_improvement", "Soil Improvement"),
                            ("general_practice", "General Practice"),
                        ],
                        max_length=30,
                        verbose_name="recommendation type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "implementation_steps",
                    models.TextField(blank=True, verbose_name="implementation steps"),
                ),
                (
                    "required_materials",
                    models.JSONField(
                        blank=True, default=list, verbose_name="required materials"
                    ),
                ),
                (
                    "estimated_cost_xaf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="estimated cost (XAF)",
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="estimated duration (days)"
                    ),
                ),
                (
                    "recommended_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="recommended start date"
                    ),
                ),
                (
                    "recommended_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="recommended end date"
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=True, verbose_name="follow up required"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="follow up date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "agronomist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="agronomy.crop",
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="agronomy.diagnostic",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="agronomy.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "db_table": "agronomy_recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("rain", "Rain Alert"),
                            ("drought", "Drought Alert"),
                            ("storm", "Storm Alert"),
                            ("flood", "Flood Alert"),
                            ("pest_risk", "Pest Risk Alert"),
                            ("disease_risk", "Disease Risk Alert"),
                        ],
                        max_length=30,
                        verbose_name="alert type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=20,
                        verbose_name="severity",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                ("alert_date", models.DateTimeField(verbose_name="alert date")),
                ("valid_until", models.DateTimeField(verbose_name="valid until")),
                (
                    "affected_area",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="affected area"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="recommendations"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="source"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_weather_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_alerts",
                        to="agronomy.field",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_alerts",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Alert",
                "verbose_name_plural": "Weather Alerts",
                "db_table": "agronomy_weather_alerts",
                "ordering": ["-alert_date"],
            },
        ),
    ]
