# Generated by Django 5.2.7 on 2025-10-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agronomy", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="weatheralert",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_alerts",
                to="organizations.organization",
            ),
        ),
    ]
