# Generated by Django 5.2.7 on 2025-10-27 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agronomy", "0002_alter_field_organization_and_more"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgronomistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="license number"
                    ),
                ),
                (
                    "license_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="license expiry"
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="years of experience"
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="specializations"
                    ),
                ),
                (
                    "expertise_areas",
                    models.JSONField(
                        blank=True, default=list, verbose_name="expertise areas"
                    ),
                ),
                (
                    "has_organic_certification",
                    models.BooleanField(
                        default=False, verbose_name="organic certification"
                    ),
                ),
                (
                    "has_pest_control_certification",
                    models.BooleanField(
                        default=False, verbose_name="pest control certification"
                    ),
                ),
                (
                    "has_soil_analysis_certification",
                    models.BooleanField(
                        default=False, verbose_name="soil analysis certification"
                    ),
                ),
                (
                    "phone_emergency",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="emergency phone"
                    ),
                ),
                (
                    "current_location",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="current location"
                    ),
                ),
                (
                    "preferred_working_hours",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="preferred working hours"
                    ),
                ),
                (
                    "max_travel_distance_km",
                    models.PositiveIntegerField(
                        default=100, verbose_name="max travel distance (km)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agronomist_profiles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agronomist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agronomist Profile",
                "verbose_name_plural": "Agronomist Profiles",
                "db_table": "agronomy_agronomist_profiles",
            },
        ),
    ]
