# Generated by Django 4.2.7 on 2025-11-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("agronomy", "0004_agronomistprofile_certification_documents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agronomistprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agronomist_profiles",
                to="core.city",
                verbose_name="city",
            ),
        ),
        migrations.AddField(
            model_name="agronomistprofile",
            name="intervention_provinces",
            field=models.ManyToManyField(
                blank=True,
                related_name="agronomists",
                to="core.province",
                verbose_name="intervention provinces",
            ),
        ),
        migrations.AddField(
            model_name="agronomistprofile",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agronomist_profiles",
                to="core.province",
                verbose_name="province",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fields",
                to="core.city",
                verbose_name="city",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fields",
                to="core.province",
                verbose_name="province",
            ),
        ),
    ]
