# Generated by Django 5.2.7 on 2025-10-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyerprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_profiles",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="preferred_suppliers",
            field=models.ManyToManyField(
                blank=True,
                related_name="preferred_by_buyers",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_as_seller",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to="organizations.organization",
            ),
        ),
    ]
