# Generated by Django 5.2.7 on 2025-10-27 09:37

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0002_alter_buyerprofile_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="business_documents",
            field=models.JSONField(
                blank=True, default=list, verbose_name="business documents"
            ),
        ),
        migrations.AddField(
            model_name="buyerprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.MinIOUserAvatarsStorage(),
                upload_to="buyers/profiles/",
                verbose_name="profile photo",
            ),
        ),
    ]
