# Generated by Django 5.2.7 on 2025-10-26 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0002_alter_organization_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="farmers.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "farmers_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farm_size_hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="farm size (hectares)",
                    ),
                ),
                (
                    "farming_experience_years",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="farming experience (years)"
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="certification number"
                    ),
                ),
                (
                    "organic_certified",
                    models.BooleanField(
                        default=False, verbose_name="organic certified"
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="specializations"
                    ),
                ),
                (
                    "crops_grown",
                    models.JSONField(
                        blank=True, default=list, verbose_name="crops grown"
                    ),
                ),
                (
                    "farm_address",
                    models.TextField(blank=True, verbose_name="farm address"),
                ),
                (
                    "farm_coordinates",
                    models.JSONField(
                        blank=True, null=True, verbose_name="farm coordinates"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="bio")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "social_media",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="social media"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profiles",
                        to="iam.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farmer Profile",
                "verbose_name_plural": "Farmer Profiles",
                "db_table": "farmers_farmer_profiles",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="SKU"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="kg", max_length=20, verbose_name="unit"),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="stock quantity"
                    ),
                ),
                (
                    "min_order_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="minimum order quantity"
                    ),
                ),
                (
                    "max_order_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="maximum order quantity"
                    ),
                ),
                (
                    "quality_grade",
                    models.CharField(
                        choices=[
                            ("premium", "Premium"),
                            ("standard", "Standard"),
                            ("economy", "Economy"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="quality grade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "harvest_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="harvest date"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="expiry date"),
                ),
                (
                    "origin_country",
                    models.CharField(
                        default="Gabon", max_length=100, verbose_name="origin country"
                    ),
                ),
                (
                    "organic_certified",
                    models.BooleanField(
                        default=False, verbose_name="organic certified"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="weight",
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(blank=True, null=True, verbose_name="dimensions"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="farmers.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "farmers_products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/images/", verbose_name="image"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="alt text"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary image"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="farmers.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "farmers_product_images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 étoile"),
                            (2, "2 étoiles"),
                            (3, "3 étoiles"),
                            (4, "4 étoiles"),
                            (5, "5 étoiles"),
                        ],
                        verbose_name="rating",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("comment", models.TextField(verbose_name="comment")),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False, verbose_name="verified purchase"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="farmers.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Review",
                "verbose_name_plural": "Product Reviews",
                "db_table": "farmers_product_reviews",
                "ordering": ["-created_at"],
                "unique_together": {("product", "buyer")},
            },
        ),
    ]
