# Generated by Django 5.2.7 on 2025-10-27 09:21

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmers", "0002_alter_farmerprofile_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                storage=apps.core.storage.MinIOProductImagesStorage(),
                upload_to="products/images/",
                verbose_name="image",
            ),
        ),
    ]
