# Generated by Django 5.2.7 on 2025-10-27 09:37

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmers", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="certification_documents",
            field=models.JSONField(
                blank=True, default=list, verbose_name="certification documents"
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="farm_photos",
            field=models.JSONField(
                blank=True, default=list, verbose_name="farm photos"
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.MinIOUserAvatarsStorage(),
                upload_to="farmers/profiles/",
                verbose_name="profile photo",
            ),
        ),
    ]
