# Generated by Django 4.2.7 on 2025-11-08 02:52

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmers", "0004_farmerprofile_certification_documents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("crop", "Produits végétaux"),
                    ("livestock", "Produits animaux (élevage)"),
                    ("fishery", "Produits animaux (pêche)"),
                    ("mixed", "Mixte"),
                ],
                default="crop",
                max_length=20,
                verbose_name="product type",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="animal_age",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[MinValueValidator(0)],
                verbose_name="animal age",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="animal_age_unit",
            field=models.CharField(
                choices=[
                    ("day", "Jour(s)"),
                    ("week", "Semaine(s)"),
                    ("month", "Mois"),
                    ("year", "Année(s)"),
                ],
                default="month",
                blank=True,
                max_length=10,
                verbose_name="animal age unit",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="animal_breed",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="animal breed"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="animal_species",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="animal species"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="animals_per_lot",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="animals per lot"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="feeding_type",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="feeding type"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="health_status",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="health status"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="processing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("live", "Vivant"),
                    ("fresh", "Frais / abattu"),
                    ("frozen", "Congelé"),
                    ("processed", "Transformé"),
                ],
                max_length=20,
                verbose_name="processing type",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("crop", "Produit végétal"),
                    ("livestock", "Produit animal - élevage"),
                    ("fishery", "Produit animal - pêche"),
                ],
                default="crop",
                max_length=20,
                verbose_name="product type",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rearing_method",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="rearing method"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slaughter_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="slaughter date"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="storage_temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="storage temperature (°C)",
            ),
        ),
    ]
