# Generated by Django 4.2.7 on 2025-11-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("farmers", "0005_category_product_type_product_animal_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farmer_profiles",
                to="core.city",
                verbose_name="city",
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farmer_profiles",
                to="core.province",
                verbose_name="province",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quality_grade",
            field=models.CharField(
                choices=[
                    ("extra", "Qualité Extra"),
                    ("class_i", "Classe I"),
                    ("class_ii", "Classe II"),
                ],
                default="standard",
                max_length=20,
                verbose_name="quality grade",
            ),
        ),
    ]
