# Generated by Django 4.2.7 on 2025-11-13 10:23

import apps.core.storage
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_alter_organization_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="SKU"),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="brand"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="model"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="stock quantity"
                    ),
                ),
                (
                    "min_order_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="minimum order quantity"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Neuf"),
                            ("used", "Occasion"),
                            ("refurbished", "Reconditionné"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="condition",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="specifications"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="in kg",
                        max_digits=8,
                        null=True,
                        verbose_name="weight",
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(blank=True, null=True, verbose_name="dimensions"),
                ),
                (
                    "power_requirement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="power requirement"
                    ),
                ),
                (
                    "warranty_period_months",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="warranty period (months)"
                    ),
                ),
                (
                    "has_maintenance_service",
                    models.BooleanField(
                        default=False, verbose_name="has maintenance service"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "db_table": "suppliers_equipment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="SKU"),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="brand"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="kg", max_length=20, verbose_name="unit"),
                ),
                (
                    "min_order_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="minimum order quantity"
                    ),
                ),
                (
                    "max_order_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="maximum order quantity"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="stock quantity"
                    ),
                ),
                (
                    "reorder_level",
                    models.PositiveIntegerField(
                        default=10, verbose_name="reorder level"
                    ),
                ),
                (
                    "quality_grade",
                    models.CharField(
                        choices=[
                            ("premium", "Premium"),
                            ("standard", "Standard"),
                            ("economy", "Economy"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="quality grade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="expiry date"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="batch number"
                    ),
                ),
                (
                    "origin_country",
                    models.CharField(
                        default="Gabon", max_length=100, verbose_name="origin country"
                    ),
                ),
                (
                    "organic_certified",
                    models.BooleanField(
                        default=False, verbose_name="organic certified"
                    ),
                ),
                (
                    "composition",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="composition"
                    ),
                ),
                (
                    "usage_instructions",
                    models.TextField(blank=True, verbose_name="usage instructions"),
                ),
                (
                    "safety_precautions",
                    models.TextField(blank=True, verbose_name="safety precautions"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Input",
                "verbose_name_plural": "Inputs",
                "db_table": "suppliers_inputs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="order number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("ready", "Ready for Pickup"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="payment status",
                    ),
                ),
                ("billing_address", models.JSONField(verbose_name="billing address")),
                ("shipping_address", models.JSONField(verbose_name="shipping address")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="subtotal"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="shipping fee",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF", max_length=3, verbose_name="currency"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="tracking number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmed at"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="shipped at"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_orders_as_farmer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_orders_as_supplier",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Order",
                "verbose_name_plural": "Supplier Orders",
                "db_table": "suppliers_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_license",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="business license"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="tax number"
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="years of experience"
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="specializations"
                    ),
                ),
                (
                    "product_categories",
                    models.JSONField(
                        blank=True, default=list, verbose_name="product categories"
                    ),
                ),
                (
                    "warehouse_address",
                    models.TextField(blank=True, verbose_name="warehouse address"),
                ),
                (
                    "warehouse_coordinates",
                    models.JSONField(
                        blank=True, null=True, verbose_name="warehouse coordinates"
                    ),
                ),
                (
                    "phone_emergency",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="emergency phone"
                    ),
                ),
                (
                    "has_organic_certification",
                    models.BooleanField(
                        default=False, verbose_name="organic certification"
                    ),
                ),
                (
                    "has_quality_certification",
                    models.BooleanField(
                        default=False, verbose_name="quality certification"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="bio")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "social_media",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="social media"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=apps.core.storage.MinIOUserAvatarsStorage(),
                        upload_to="suppliers/profiles/",
                        verbose_name="profile photo",
                    ),
                ),
                (
                    "business_documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="business documents"
                    ),
                ),
                (
                    "warehouse_photos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="warehouse photos"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profiles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Profile",
                "verbose_name_plural": "Supplier Profiles",
                "db_table": "suppliers_supplier_profiles",
            },
        ),
        migrations.CreateModel(
            name="SupplierOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="unit price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total price"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="suppliers.supplierorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Order Item",
                "verbose_name_plural": "Supplier Order Items",
                "db_table": "suppliers_order_items",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Entrée"),
                            ("out", "Sortie"),
                            ("adjustment", "Ajustement"),
                            ("return", "Retour"),
                        ],
                        max_length=20,
                        verbose_name="movement type",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="quantity")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference number"
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="reason"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "stock_before",
                    models.PositiveIntegerField(verbose_name="stock before"),
                ),
                (
                    "stock_after",
                    models.PositiveIntegerField(verbose_name="stock after"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "db_table": "suppliers_stock_movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InputImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=apps.core.storage.MinIOProductImagesStorage(),
                        upload_to="suppliers/inputs/images/",
                        verbose_name="image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="alt text"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary image"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "input_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="suppliers.input",
                    ),
                ),
            ],
            options={
                "verbose_name": "Input Image",
                "verbose_name_plural": "Input Images",
                "db_table": "suppliers_input_images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InputCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("seed", "Semences"),
                            ("pesticide", "Produits phytosanitaires"),
                            ("fertilizer", "Engrais"),
                            ("feed", "Aliments pour bétail"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="category type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="suppliers.inputcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Input Category",
                "verbose_name_plural": "Input Categories",
                "db_table": "suppliers_input_categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="input",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inputs",
                to="suppliers.inputcategory",
            ),
        ),
        migrations.AddField(
            model_name="input",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_inputs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="input",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_inputs",
                to="organizations.organization",
            ),
        ),
        migrations.CreateModel(
            name="EquipmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=apps.core.storage.MinIOProductImagesStorage(),
                        upload_to="suppliers/equipment/images/",
                        verbose_name="image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="alt text"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary image"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="suppliers.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Image",
                "verbose_name_plural": "Equipment Images",
                "db_table": "suppliers_equipment_images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="suppliers.equipmentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Category",
                "verbose_name_plural": "Equipment Categories",
                "db_table": "suppliers_equipment_categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipment",
                to="suppliers.equipmentcategory",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_equipment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_equipment",
                to="organizations.organization",
            ),
        ),
        migrations.CreateModel(
            name="SupplierReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 étoile"),
                            (2, "2 étoiles"),
                            (3, "3 étoiles"),
                            (4, "4 étoiles"),
                            (5, "5 étoiles"),
                        ],
                        verbose_name="rating",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("comment", models.TextField(verbose_name="comment")),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False, verbose_name="verified purchase"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Review",
                "verbose_name_plural": "Supplier Reviews",
                "db_table": "suppliers_reviews",
                "ordering": ["-created_at"],
                "unique_together": {("content_type", "object_id", "farmer")},
            },
        ),
        migrations.AddIndex(
            model_name="supplierorder",
            index=models.Index(
                fields=["farmer", "status"], name="suppliers_o_farmer__8f88bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierorder",
            index=models.Index(
                fields=["supplier", "status"], name="suppliers_o_supplie_3750df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierorder",
            index=models.Index(
                fields=["order_number"], name="suppliers_o_order_n_a0c725_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="suppliers_s_content_044e04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["organization", "movement_type"],
                name="suppliers_s_organiz_739bdb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="input",
            index=models.Index(
                fields=["organization", "status"], name="suppliers_i_organiz_e7afbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="input",
            index=models.Index(
                fields=["category", "status"], name="suppliers_i_categor_191a8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="input",
            index=models.Index(fields=["sku"], name="suppliers_i_sku_c97351_idx"),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["organization", "status"], name="suppliers_e_organiz_fc7808_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["category", "status"], name="suppliers_e_categor_88f478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["sku"], name="suppliers_e_sku_81d0db_idx"),
        ),
    ]
