# Generated by Django 4.2.7 on 2025-11-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_profiles",
                to="core.city",
                verbose_name="city",
            ),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_profiles",
                to="core.province",
                verbose_name="province",
            ),
        ),
    ]
