# Generated by Django 5.2.7 on 2025-10-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0002_alter_organization_country"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="organizations.organization",
            ),
        ),
    ]
