# Generated by Django 5.2.7 on 2025-10-26 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agronomy", "0002_alter_field_organization_and_more"),
        ("buyers", "0002_alter_buyerprofile_organization_and_more"),
        ("farmers", "0002_alter_farmerprofile_organization_and_more"),
        ("iam", "0003_alter_membership_organization_and_more"),
        (
            "transport",
            "0002_alter_driver_organization_alter_route_organization_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
