# Generated by Django 5.2.7 on 2025-10-27 09:37

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0004_delete_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.MinIOUserAvatarsStorage(),
                upload_to="users/avatars/",
                verbose_name="avatar",
            ),
        ),
    ]
