# Generated by Django 5.2.7 on 2025-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0005_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("farmer", "Farmer"),
                    ("buyer", "Buyer"),
                    ("transporter", "Transporter"),
                    ("agronomist", "Agronomist"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                ],
                max_length=50,
                verbose_name="role",
            ),
        ),
    ]
