# Generated by Django 4.2.7 on 2025-11-04 16:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buyers", "0003_buyerprofile_business_documents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="payment ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("airtel_money", "Airtel Money"),
                            ("moov_money", "Moov Money"),
                            ("stripe", "Stripe"),
                        ],
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        help_text="Référence retournée par le provider de paiement",
                        max_length=255,
                        null=True,
                        verbose_name="provider reference",
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de transaction unique du provider",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="provider transaction ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Métadonnées additionnelles du paiement",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Raison de l'échec du paiement",
                        verbose_name="failure reason",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="failed at"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="buyer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="buyers.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="event ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("airtel_money", "Airtel Money"),
                            ("moov_money", "Moov Money"),
                            ("stripe", "Stripe"),
                        ],
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type d'événement (ex: payment.succeeded, payment.failed)",
                        max_length=100,
                        verbose_name="event type",
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de transaction du provider pour identifier le paiement",
                        max_length=255,
                        null=True,
                        verbose_name="provider transaction ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Payload complet du webhook", verbose_name="payload"
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="Signature du webhook pour vérification",
                        max_length=500,
                        null=True,
                        verbose_name="signature",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de tentatives de traitement",
                        verbose_name="attempts",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="error message"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="received at"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last attempt at"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payments.payment",
                        verbose_name="payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "payments_webhook_events",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="payments_we_event_i_a3da34_idx"
                    ),
                    models.Index(
                        fields=["provider", "status"],
                        name="payments_we_provide_e1d07a_idx",
                    ),
                    models.Index(
                        fields=["provider_transaction_id"],
                        name="payments_we_provide_9a6890_idx",
                    ),
                    models.Index(
                        fields=["payment", "status"],
                        name="payments_we_payment_8ef6fd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="attempt number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="error message"
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Réponse complète du provider",
                        verbose_name="provider response",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="payments.payment",
                        verbose_name="payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Attempt",
                "verbose_name_plural": "Payment Attempts",
                "db_table": "payments_payment_attempts",
                "ordering": ["-created_at"],
                "unique_together": {("payment", "attempt_number")},
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_id"], name="payments_pa_payment_c3e44d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="payments_pa_order_i_3fb38a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider", "status"], name="payments_pa_provide_65da08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider_transaction_id"],
                name="payments_pa_provide_795161_idx",
            ),
        ),
    ]
