# Generated by Django 4.2.7 on 2025-11-04 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buyers", "0003_buyerprofile_business_documents_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_order_i_3fb38a_idx",
        ),
        migrations.AddField(
            model_name="payment",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type de transaction (Order, Shipment, etc.)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID de la transaction (Order.id ou Shipment.id)",
                null=True,
                verbose_name="object id",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisateur qui effectue le paiement",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="payer",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("order", "Order Payment"), ("shipment", "Shipment Payment")],
                help_text="Type de paiement (order, shipment, etc.)",
                max_length=20,
                null=True,
                verbose_name="payment type",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="buyer",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="buyers.order",
                verbose_name="order",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["content_type", "object_id", "status"],
                name="payments_pa_content_fd0bf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_type", "status"], name="payments_pa_payment_5fb9ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payer", "status"], name="payments_pa_payer_i_5c42dd_idx"
            ),
        ),
    ]
