# Generated by Django 5.2.7 on 2025-10-26 00:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
        ("iam", "0002_alter_organization_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="license number"
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("B", "License B (Car)"),
                            ("C", "License C (Truck)"),
                            ("CE", "License CE (Truck + Trailer)"),
                            ("D", "License D (Bus)"),
                        ],
                        max_length=10,
                        verbose_name="license type",
                    ),
                ),
                ("license_expiry", models.DateField(verbose_name="license expiry")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_duty", "On Duty"),
                            ("off_duty", "Off Duty"),
                            ("suspended", "Suspended"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "current_location",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="current location"
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="years experience"
                    ),
                ),
                (
                    "has_hazmat_certification",
                    models.BooleanField(
                        default=False, verbose_name="has hazmat certification"
                    ),
                ),
                (
                    "has_refrigerated_certification",
                    models.BooleanField(
                        default=False, verbose_name="has refrigerated certification"
                    ),
                ),
                (
                    "phone_emergency",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="emergency phone"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="iam.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "db_table": "transport_drivers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "origin_city",
                    models.CharField(max_length=100, verbose_name="origin city"),
                ),
                (
                    "origin_country",
                    models.CharField(max_length=100, verbose_name="origin country"),
                ),
                (
                    "origin_coordinates",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="origin coordinates"
                    ),
                ),
                (
                    "destination_city",
                    models.CharField(max_length=100, verbose_name="destination city"),
                ),
                (
                    "destination_country",
                    models.CharField(
                        max_length=100, verbose_name="destination country"
                    ),
                ),
                (
                    "destination_coordinates",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="destination coordinates"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="distance (km)"
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="estimated duration (hours)",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="base price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "required_vehicle_type",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="required vehicle type"
                    ),
                ),
                (
                    "requires_refrigeration",
                    models.BooleanField(
                        default=False, verbose_name="requires refrigeration"
                    ),
                ),
                (
                    "requires_special_equipment",
                    models.BooleanField(
                        default=False, verbose_name="requires special equipment"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "db_table": "transport_routes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="tracking number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("delayed", "Delayed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "scheduled_pickup_date",
                    models.DateTimeField(verbose_name="scheduled pickup date"),
                ),
                (
                    "scheduled_delivery_date",
                    models.DateTimeField(verbose_name="scheduled delivery date"),
                ),
                (
                    "actual_pickup_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="actual pickup date"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="actual delivery date"
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="in kg",
                        max_digits=8,
                        verbose_name="total weight",
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="in m³",
                        max_digits=8,
                        verbose_name="total volume",
                    ),
                ),
                (
                    "transport_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="transport cost"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "special_instructions",
                    models.TextField(blank=True, verbose_name="special instructions"),
                ),
                (
                    "requires_signature",
                    models.BooleanField(
                        default=True, verbose_name="requires signature"
                    ),
                ),
                (
                    "requires_photo_proof",
                    models.BooleanField(
                        default=False, verbose_name="requires photo proof"
                    ),
                ),
                (
                    "current_location",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="current location"
                    ),
                ),
                (
                    "delivery_proof",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="delivery proof"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="transport.driver",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="buyers.order",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="transport.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "db_table": "transport_shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="status")),
                (
                    "location",
                    models.JSONField(blank=True, default=dict, verbose_name="location"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="transport.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Tracking",
                "verbose_name_plural": "Shipment Tracking Events",
                "db_table": "transport_shipment_tracking",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="license plate"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("truck", "Truck"),
                            ("van", "Van"),
                            ("refrigerated_truck", "Refrigerated Truck"),
                            ("trailer", "Trailer"),
                            ("motorcycle", "Motorcycle"),
                            ("bicycle", "Bicycle"),
                        ],
                        max_length=30,
                        verbose_name="vehicle type",
                    ),
                ),
                ("make", models.CharField(max_length=100, verbose_name="make")),
                ("model", models.CharField(max_length=100, verbose_name="model")),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                        verbose_name="year",
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="in kg",
                        max_digits=8,
                        verbose_name="max weight",
                    ),
                ),
                (
                    "max_volume",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="in m³",
                        max_digits=8,
                        verbose_name="max volume",
                    ),
                ),
                (
                    "max_pallets",
                    models.PositiveIntegerField(default=0, verbose_name="max pallets"),
                ),
                (
                    "has_refrigeration",
                    models.BooleanField(
                        default=False, verbose_name="has refrigeration"
                    ),
                ),
                (
                    "has_tracking",
                    models.BooleanField(default=True, verbose_name="has tracking"),
                ),
                (
                    "has_loading_equipment",
                    models.BooleanField(
                        default=False, verbose_name="has loading equipment"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In Use"),
                            ("maintenance", "Maintenance"),
                            ("out_of_service", "Out of Service"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "current_location",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="current location"
                    ),
                ),
                (
                    "insurance_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="insurance number"
                    ),
                ),
                (
                    "insurance_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="insurance expiry"
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="inspection date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "transport_vehicles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offered_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="offered price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "estimated_pickup_date",
                    models.DateTimeField(verbose_name="estimated pickup date"),
                ),
                (
                    "estimated_delivery_date",
                    models.DateTimeField(verbose_name="estimated delivery date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="transport.driver",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="transport.shipment",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_offers",
                        to="iam.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="transport.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport Offer",
                "verbose_name_plural": "Transport Offers",
                "db_table": "transport_offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="transport.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["organization", "is_active"],
                name="transport_r_organiz_894c86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["origin_city", "destination_city"],
                name="transport_r_origin__5e7e5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["organization", "status"], name="transport_v_organiz_ddaeac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["vehicle_type", "status"], name="transport_v_vehicle_183f78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["license_plate"], name="transport_v_license_549513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["status", "priority"], name="transport_s_status_7fff32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["tracking_number"], name="transport_s_trackin_4787aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["scheduled_pickup_date"], name="transport_s_schedul_f09331_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["scheduled_delivery_date"],
                name="transport_s_schedul_f55641_idx",
            ),
        ),
    ]
