# Generated by Django 5.2.7 on 2025-10-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drivers",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="transportoffer",
            name="transporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_offers",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="organizations.organization",
            ),
        ),
    ]
