# Generated by Django 5.2.7 on 2025-10-27 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        (
            "transport",
            "0002_alter_driver_organization_alter_route_organization_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransporterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="license number"
                    ),
                ),
                (
                    "license_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="license expiry"
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="years of experience"
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="specializations"
                    ),
                ),
                (
                    "service_areas",
                    models.JSONField(
                        blank=True, default=list, verbose_name="service areas"
                    ),
                ),
                (
                    "has_hazmat_certification",
                    models.BooleanField(
                        default=False, verbose_name="hazmat certification"
                    ),
                ),
                (
                    "has_refrigerated_certification",
                    models.BooleanField(
                        default=False, verbose_name="refrigerated certification"
                    ),
                ),
                (
                    "has_oversized_certification",
                    models.BooleanField(
                        default=False, verbose_name="oversized certification"
                    ),
                ),
                (
                    "phone_emergency",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="emergency phone"
                    ),
                ),
                (
                    "current_location",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="current location"
                    ),
                ),
                (
                    "preferred_working_hours",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="preferred working hours"
                    ),
                ),
                (
                    "max_distance_km",
                    models.PositiveIntegerField(
                        default=500, verbose_name="max distance (km)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transporter_profiles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transporter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transporter Profile",
                "verbose_name_plural": "Transporter Profiles",
                "db_table": "transport_transporter_profiles",
            },
        ),
    ]
