# Generated by Django 5.2.7 on 2025-10-27 09:37

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0003_transporterprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporterprofile",
            name="license_documents",
            field=models.JSONField(
                blank=True, default=list, verbose_name="license documents"
            ),
        ),
        migrations.AddField(
            model_name="transporterprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.MinIOUserAvatarsStorage(),
                upload_to="transporters/profiles/",
                verbose_name="profile photo",
            ),
        ),
        migrations.AddField(
            model_name="transporterprofile",
            name="vehicle_photos",
            field=models.JSONField(
                blank=True, default=list, verbose_name="vehicle photos"
            ),
        ),
    ]
