# Generated by Django 4.2.7 on 2025-11-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0004_transporterprofile_license_documents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="payment status",
            ),
        ),
    ]
