# Generated by Django 4.2.7 on 2025-11-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("transport", "0005_shipment_payment_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="route",
            name="transport_r_origin__5e7e5a_idx",
        ),
        migrations.RemoveField(
            model_name="route",
            name="destination_city",
        ),
        migrations.RemoveField(
            model_name="route",
            name="origin_city",
        ),
        migrations.AddField(
            model_name="route",
            name="destination_city_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routes_destination",
                to="core.city",
                verbose_name="destination city",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="destination_city_old",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="destination city (old)"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="origin_city_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routes_origin",
                to="core.city",
                verbose_name="origin city",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="origin_city_old",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="origin city (old)"
            ),
        ),
        migrations.AddField(
            model_name="transporterprofile",
            name="service_cities",
            field=models.ManyToManyField(
                blank=True,
                related_name="transporters",
                to="core.city",
                verbose_name="service cities",
            ),
        ),
        migrations.AddField(
            model_name="transporterprofile",
            name="service_provinces",
            field=models.ManyToManyField(
                blank=True,
                related_name="transporters",
                to="core.province",
                verbose_name="service provinces",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="destination_country",
            field=models.CharField(
                default="Gabon", max_length=100, verbose_name="destination country"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="origin_country",
            field=models.CharField(
                default="Gabon", max_length=100, verbose_name="origin country"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["origin_city_fk", "destination_city_fk"],
                name="transport_r_origin__50c220_idx",
            ),
        ),
    ]
