# Generated by Django 5.2.7 on 2025-10-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cooperative", "Cooperative"),
                            ("enterprise", "Enterprise"),
                            ("ngo", "NGO"),
                            ("government", "Government"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Gabon", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="industry"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basic",
                        max_length=50,
                        verbose_name="plan",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="settings"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organizations/logos/",
                        verbose_name="logo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
    ]
