# Generated by Django 5.2.7 on 2025-10-27 09:21

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.MinIOOrganizationLogosStorage(),
                upload_to="organizations/logos/",
                verbose_name="logo",
            ),
        ),
    ]
